[env:esp32dev]
platform = espressif32
board = esp32dev
board_build.flash_size = 4MB
board_build.f_cpu = 240000000L
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM5
lib_ldf_mode = deep+
lib_deps =
	olikraus/U8g2
	thijse/ArduinoLog@^1.1.1
	tzapu/WiFiManager@^2.0.16
	bblanchon/ArduinoJson@^6.21.3
	adafruit/Adafruit BME280 Library@^2.3.0
	knolleary/PubSubClient@^2.8
	claws/BH1750@^1.3.0
build_flags =
	-I lib
	-I include
	-I "include/ISCS"
	-I "include/MSP20"
	-I ".pio/libdeps/esp32dev/BH1750"
	-I ".pio/libdeps/esp32dev/Adafruit BME280 Library"
	-I ".pio/libdeps/esp32dev/Adafruit BusIO"
	-I ".pio/libdeps/esp32dev/Adafruit Unified Sensor"
	-DCONFIG_FREERTOS_USE_TRACE_FACILITY=1
	-DCONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
	-DCONFIG_FREERTOS_VTASKLIST_INCLUDE_COREID=1
	-DMQTT_MAX_PACKET_SIZE=1024
build_src_filter =
	+<*>
	+<../lib/*/>
	+<../include/ISCS/>
	+<../include/MSP20/>